### ISSUE TITLE
vreemd gedrag van builder

### ISSUE THREAD

**Issue by louisgosschalk** [clanghout/Health-Informatics-3#114]
Stel je maakt een builder waarmee je 2 aparte tables wilt maken, moet je opletten anders maak je 2 keer dezelfde table.

bijvoorbeeld:
initialiseer builder
maak rows aan
maak table
maak extra rows
maak table

dit retourneert twee dezelfde tables, terwijl je dus twee tables wilt waarvan de tweede een extensie is van de eerste.

na het aanmaken van de eerste table opnieuw de builder initialiseren en de eerste rows opnieuw aanmaken is een work-around

**Comment by JensLangerak** [comment]
Dit is op te lossen. Maar dit is iets dat alleen in testen voorkomt. In normaal gebruik, maak je een nieuwe builder voor iedere table die je inleest en met die gedachte is de builder ook gemaakt. Dus die workaround is eigenlijk geen workaround maar gewoon de correcte manier van gebruiken.

**Comment by louisgosschalk** [comment]
Klopt overigens ook niet wat ik zeg. 
Voor twee aparte tables gewoon twee aparte builders gebruiken, anders gebeuren er hele, hele rare dingen.
