### ISSUE TITLE
Meerdere tabellen moeilijk

### ISSUE THREAD

**Issue by Boudewijn26** [clanghout/Health-Informatics-3#119]
De CombinedDataTable is niet een echte join operatie, dus daar hebben we een oplossing voor nodig.

**Comment by JensLangerak** [comment]
Join kan worden gedefinieerd als combinedDataTable.export("name").

**Comment by Boudewijn26** [comment]
Prima, maar dan moeten we wel in de parser dingen voor bedenken.
