### ISSUE TITLE
LagSequentialAnalysis sorteren

### ISSUE THREAD

**Issue by louisgosschalk** [clanghout/Health-Informatics-3#147]
Het sorteren in de LSA wordt nu gedaan door een functie in de LSA. Hiervoor komt een globale functie in de datatable om te sorteren, zodra deze dus bestaat moet de functie in de LSA vervangen worden door deze globale functie.

**Comment by Boudewijn26** [comment]
Je hebt ook nog een SortProcess nodig, kan je die niet gewoon gebruiken? Dan wordt DataTable niet onnodig groot.

**Comment by louisgosschalk** [comment]
sortprocess built & LSA being rebuilt
